wandb_version: 1

function:
  desc: null
  value: Ackley
Dim:
  desc: null
  value: 1D
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717060933
    t:
      1:
      - 1
      - 30
      - 55
      2:
      - 1
      - 30
      - 55
      3:
      - 16
      - 23
      - 24
      4: 3.10.13
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
