problem_name: test_function
save_dir: ./logs/testfunction/sphere_test
seed: 0

exp_settings:
  n_exp: 5
  n_iter: 100
  batch_size: 5

bo_settings:
  algorithm: [random, qEI, SNES, piqEI]
  beta: 1.
  var_prior: 100.
  num_restarts: 10
  mc_samples: 256
  raw_samples: 512

problem_settings:
  function: sphere
  noise: 0.
  dim: 2
  initial_bounds: 10.