label: test_function
save_dir: ./logs/testfunction/ackley

bo_settings:
  seed: [0, 1]
  beta: 1.
  var_prior: [1., 100., 1000.]
  n_trials: 3
  num_restarts: 10
  n_iter: 20
  mc_samples: 256
  raw_samples: 512
  batch_size: 3

problem_settings:
  test_function: "ackley"
  noise: [0., 1.]
  dim: [2, 5, 10]