problem_name: test_function
save_dir: ./logs/testfunction/rosenbrock_dim5
seed: 0

exp_settings:
  n_exp: 15
  n_iter: 100
  batch_size: 5

bo_settings:
  algorithm: [random, qEI, SNES, piqEI]
  beta: 1.
  var_prior: 100.
  num_restarts: 10
  mc_samples: 256
  raw_samples: 512

problem_settings:
  test_function: "rosenbrock"
  noise: 0.
  dim: 5
  initial_bounds: 10.