problem_name: test_function #test_function, airfoil
save_dir: ./logs/test_function/ackley_dim2
seed: 0

exp_settings:
  n_exp: 5
  n_iter: 100
  batch_size: 5

bo_settings:
  algorithm: "quad"  #[random, qEI, SNES, piqEI, quad]
  beta: 1. #For piqei
  var_prior: 10. #For piqEI or quad, initial distribution
  num_restarts: 10 #For qEI and piqEI
  mc_samples: 256 #For qEI and piqEI
  raw_samples: 512 #For qEI and piqEI
  policy: "ivr_rand" # For quad in [ivr, ivr_rand, mi, mi_rand, us, us_rand, vdc, bmc]
  step_size: 3. # For quad, step size gradient

problem_settings:
  function: "ackley" # Name of the function in [airfoil, rosenbrock, sphere, ackley]
  noise: 0.
  dim: 2
  initial_bounds: 10.