problem_name: test_function #test_function, airfoil
save_dir: ./logs/test_function
seed: 0
verbose_synthesis: 1
gpu: 0

exp_settings:
  n_exp: 1
  n_iter: 15
  batch_size: 5
  n_init: 5

## Change config for algorithm setting
alg_settings:
  algorithm: ["quad", "SNES"] #["quad", "SNES", "random", "qEI", "piqEI"]  #[random, qEI, SNES, piqEI, quad]
  verbose: 10
  piqEI:
    beta: 1.
    var_prior: [10.]
    num_restarts: 10 #For qEI and piqEI
    mc_samples: 256 #For qEI and piqEI
    raw_samples: 512 #For qEI and piqEI
    batch_acq: 5 # Number of batches used to evaluate the acquisition function at the same time
  qEI:
    num_restarts: 10 #For qEI and piqEI
    mc_samples: 256 #For qEI and piqEI
    raw_samples: 512 #For qEI and piqEI
    batch_acq: 5 # Number of batches used to evaluate the acquisition function at the same time
  quad:
    var_prior: [10.]
    candidates_vr: 5000
    policy: "ei" # ["wolfe", "ei", "armijo"]
    c1: 0.0001
    c2: 0.9
    t_max: 100
    budget: 500
    manifold: False
    gradient_direction: "expected" #["sample", "mpd"]
  SNES:
    var_prior: [10.]
   #For piqei

problem_settings:
  function: "ackley" # Name of the function in [airfoil, rosenbrock, sphere, ackley]
  noise: 0.
  dim: 1
  initial_bounds: 10.