problem_name: test_function #test_function, airfoil, latent_space
save_dir: ./logs/test_function
seed: 0
verbose_synthesis: 0
gpu: 0
overwrite: True

exp_settings:
  n_exp: 2
  n_iter: 50
  n_init: 3 # Has to be equal to batch size for evo algo

## Change config for algorithm setting
alg_settings:
  algorithm: "probES" #["probES", "ES", "random", "qEI", "piqEI"] 
  verbose: 10
  batch_size: 3
  piqEI:
    beta: 1.
    mean_prior: -1.
    std_prior: 3.
    num_restarts: 10 #For qEI and piqEI
    mc_samples: 256 #For qEI and piqEI
    raw_samples: 512 #For qEI and piqEI
    batch_acq: 5 # Number of batches used to evaluate the acquisition function at the same time
  qEI:
    num_restarts: 10 #For qEI and piqEI
    mc_samples: 256 #For qEI and piqEI
    raw_samples: 512 #For qEI and piqEI
    batch_acq: 5 # Number of batches used to evaluate the acquisition function at the same time
  probES:
    mean_prior: -1.
    std_prior: 3.
    candidates_vr: 300
    type: "CMAES" # One of ["SNES", "XNES", "CMAES"]
    lr: 1.
    policy: "constant" # ["wolfe", "ei", "ei_bi", "armijo", "constant", "wolfe_ei", "armijo_ei"]
    aqc_type: "random" # ["none", "random", "optimized_bound", "optimized_mahalanobis"] none = random samples, "random" = optimized via random samples, "optimized_bound": optimization on full bounds, "optimized_mahalanobis": optimised on subbounds
    gradient: "expected" # ["expected", "sampled"]
    c1: 0.0001
    c2: 0.9
    t_min: 0.5
    t_max: 2
    budget: 30
    mahalanobis: True
    num_restarts: 10 #For qEI and piqEI
    mc_samples: 256 #For qEI and piqEI
    raw_samples: 512 #For qEI and piqEI
    batch_acq: 5 # Number of batches used to evaluate the acquisition function at the same time
  ES:
    std_prior: [1., 3.]
    mean_prior: -1.
    type: ["SNES", "XNES"] # One of ["SNES", "XNES", CMAES]
  random:
    std_prior: 3.
    mean_prior: 1.

problem_settings:
  function: "ackley" # Name of the function in [airfoil, rosenbrock, sphere, ackley, rastrigin, function_1, mountains, sin3] or ["Heart Disease", "Wine Quality", "Student Performance", "Forest Fires", "Computer Hardware", "Breast Cancer Wisconsin (Prognostic)", "Fertility", "Risk Factor Prediction of Chronic Kidney Disease", "Algerian Forest Fires", "Facebook Metrics", "Stock Portfolio Performance", "ISTANBUL STOCK EXCHANGE", "Air Quality", "Estimation of Obesity Levels Based On Eating Habits and Physical Condition", "Individual Household Electric Power Consumption", "AI4I 2020 Predictive Maintenance Dataset", "Concrete Compressive Strength", "Appliances Energy Prediction", "Combined Cycle Power PlantCombined Cycle Power Plant", "Iranian Churn", "Airfoil Self-Noise", "Superconductivty Data", "Gas Turbine CO and NOx Emission Data Set", "Pedestrians in Traffic"]
  noise_std: 10.
  dim: 2 # Irrelevant for latent space problem
  initial_bounds: 10.