problem_name: test_function #test_function, airfoil
save_dir: ./logs/test_function/
seed: 0

exp_settings:
  n_exp: 20
  n_iter: 100
  batch_size: 5

bo_settings:
  algorithm: ["random", "qEI", "SNES", "piqEI", "quad"]  #[random, qEI, SNES, piqEI, quad]
  beta: 1. #For piqei
  var_prior: 10. #For piqEI or quad, initial distribution
  num_restarts: 10 #For qEI and piqEI
  mc_samples: 256 #For qEI and piqEI
  raw_samples: 512 #For qEI and piqEI
  batch_acq: 5 # Number of batches used to evaluate the acquisition function at the same time
  verbose: 10

problem_settings:
  function: ["ackley", "rosenbrock", "sphere"] # Name of the function in [airfoil, rosenbrock, sphere, ackley]
  noise: [0., 0.1, 0.2]
  dim: [1, 2, 5, 10]
  initial_bounds: [1., 10.]